spring:
  datasource:
    url: jdbc:mysql://localhost:3306/treeholedb?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: 040918
    driver-class-name: com.mysql.cj.jdbc.Driver
  thymeleaf:
    cache: false  # 开启模板缓存（默认值：true），开发中关闭模板页面缓存
    prefix: classpath:/templates/
    suffix: .html
    enabled: true
  devtools:
    restart:
      enabled: true
      additional-paths: src/main/java